## TO DO - placeholder for src/data-preparation/*.py
## set local path and s3 bucket (later)
local_storage:
  raw: 
    path: dataset/transact_train.txt
    separator: '|'
  reformat:
    path: dataset/preprocessed/transact_train_reformat.csv
    separator: ','
  train_set:
    path: dataset/preprocessed/df_train.csv
    separator: ','
  test_set:
    path: dataset/preprocessed/df_test.csv
    separator: ','

strategy:
  remove_outliers: True
  test_proportion: 0.3
  random_state: 121